set shell := ["powershell.exe", "-c"]

test:
    go test -vet=all -cover -coverprofile cover.out ./...

check:
    go vet ./...
    staticcheck ./...
    errcheck ./internal/...

coverage-html:
    go tool cover -html cover.out -o cover.html
